language: rust
sudo: required
dist: trusty

rust:
  - stable

cache: cargo

script:
  - cargo build
  - cargo test

after_success: |
  docker run --security-opt seccomp=unconfined    \
        -v "$(pwd):/volume"                       \
        xd009642/tarpaulin                        \
        cargo tarpaulin --out Xml
  case "$CODECOV_TOKEN" in
    '{'*)
        ;;
    *)
      bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage report to codecov.io"
        ;;
  esac
